// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3oLCtCVmaFiIt4jbI38nKnmrRzZouqYY',
    appId: '1:1036305094882:web:09ee6c7dd4cc2465f5a6bb',
    messagingSenderId: '1036305094882',
    projectId: 'music-fan-f9a45',
    authDomain: 'music-fan-f9a45.firebaseapp.com',
    storageBucket: 'music-fan-f9a45.appspot.com',
    measurementId: 'G-JRHQW11TGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU0kzXKAGS4OElmxpKDhqphaYo2fhabOU',
    appId: '1:1036305094882:android:840b194155f9836cf5a6bb',
    messagingSenderId: '1036305094882',
    projectId: 'music-fan-f9a45',
    storageBucket: 'music-fan-f9a45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCknJKaEe5i7yPkibq4qoNRzx1rYujAbP8',
    appId: '1:1036305094882:ios:b004db34bf394dbaf5a6bb',
    messagingSenderId: '1036305094882',
    projectId: 'music-fan-f9a45',
    storageBucket: 'music-fan-f9a45.appspot.com',
    iosClientId: '1036305094882-o8ldbfmlago0b19qjs3a8f3l7n7vbtpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicFun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCknJKaEe5i7yPkibq4qoNRzx1rYujAbP8',
    appId: '1:1036305094882:ios:b004db34bf394dbaf5a6bb',
    messagingSenderId: '1036305094882',
    projectId: 'music-fan-f9a45',
    storageBucket: 'music-fan-f9a45.appspot.com',
    iosClientId: '1036305094882-o8ldbfmlago0b19qjs3a8f3l7n7vbtpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicFun',
  );
}
